title: Don't Crash

header_pages:
 - index.md
 - ImitationLearning.md
 - ReinforcementLearning.md
 - ComputerVision.md

# theme: jekyll-theme-merlot
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
